### PR TITLE
Added functionality and tests to determine sinks in a graph and check…

### PR DESCRIPTION
**Pull request by AlexeiQ**
… whether the graph is connected. Did also a small refactoring for better understandability of the Graph methods

### CODE REVIEW

**Comment by szabta89** [comment]
Looks good, a few comments:
`isConnected`

**Comment by AlexeiQ** [comment]
I used the visited-hashmap, because the algorithm needs to check lots of times, whether a node is already queued and with a set I would need to search/find the value each time instead of accessing it directly by key, wouldn't I?

**Comment by szabta89** [comment]
You should just add the elements to the set once it is visited. This is an O(1) operation. Then, asking the set if an element is contained (visited) is another O(1) operation.

**Comment by szabta89** [comment]
This looks good to me. We can merge this once the build is fixed.

**Pull request merged**
