### PR TITLE
Documentation improvements

### PR DESCRIPTION
**Pull request by alexanderpann**
- also fixes https://github.com/mbeddr/mbeddr.core/issues/2386

### CODE REVIEW

**Review by HeikoBecker — COMMENTED** [review]
Thanks a lot for the improvements. 

One small comment from my end:
Why is this model added? `Aaaaaa` looks strange
image

**Comment by alexanderpann** [comment]
> Why is this model added?

It was wondered as well but it is just a test preferences page with an unfortunate name.

**Review by HeikoBecker — APPROVED** [review]
As we agreed, this is good to be merged once the `Aaaa` name is changed.

**Comment by alexanderpann** [comment]
I'll make the name change in maintenance/mps20213.

**Pull request merged**
