### PR TITLE
Add Caching mechanism (#2547)

### PR DESCRIPTION
**Pull request by dbinkele**
solves #2547

### CODE REVIEW

**Review by alexanderpann — CHANGES_REQUESTED** [review]
Thanks for the addition! I just had a quick look: 

- You have to somehow derive the JBR executable from https://github.com/mbeddr/mbeddr.core/blob/ee1a4815061c27d3101bede860652e781f793058/build.gradle#L14 to not duplicate the logic.
- I really do not like seeing code for locking in our platform. Can you implemented is similar like [here](http://127.0.0.1:63320/node?ref=r%3A095345ad-6627-42ca-9d3f-fc1b2d9fbd61%28de.itemis.mps.editor.diagram.runtime.model%29%2F1993059304082831836) with a runnable? I am not 100% sure, but I believe marking the boolean variable as volatile should also be enough.

btw, you can use new singleton() from the collections language.

**Comment by alexanderpann** [comment]
@dbinkele  I didn't understand your code with the locking at all, it doesn't look right to me.  I pushed a commit. Can you see if the change would be okay for you?

**Comment by dbinkele** [comment]
> @dbinkele I didn't understand your code with the locking at all, it doesn't look right to me. I pushed a commit. Can you see if the change would be okay for you?

@alexanderpann This changes the semantics. The lock was there to make sure that Thread A is running in the 'withCachedLogicalChildren'-Environment and any Thread B who wants to do so as well must wait until A is finished. But both would do the caching. Now only does the caching, B starts  without waiting and probably does no caching ....

**Comment by alexanderpann** [comment]
@dbinkele B does wait, I added another test case but I can't show a counter example where it doesn't work. The current thread blocks until it calls unlock. You can check the output of the second test.

**Review by alexanderpann — DISMISSED** [review]

**Pull request merged**
