### PR TITLE
show comprehensible error message if not building with java 8

### PR DESCRIPTION
**Pull request by abstraktor**
@coolya

### CODE REVIEW

**Comment by sergej-koscejev** [comment]
I was requested to review this but I'm missing context. @abstraktor why is this needed? What happens without this check?

**Comment by abstraktor** [comment]
Without the check, it fails with an error message close to „I can’t find a JDK in the folder: “ and then pointing me to my JAVA_HOME.

The confusing part is, that this path actually contains a JDK, but for java 10. So it was just not the version it was looking for. If you would like me to, I can reproduce it on monday and post the message here.

**Comment by abstraktor** [comment]
For completeness sake, here the message without this patch:

```
* What went wrong:
A problem occurred evaluating project ':build:com.mbeddr'.
> Was not able to locate jdk home folder. Use 'jdk_home' project variable to specify JDK location explicitly. Current JAVA_HOME is: /Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home
```

**Comment by coolya** [comment]
Sorry for being late to the party but had lot's of other stuff on my todo stack. 

I tried if you could get rid of the code that manually tries to locate the `tools.jar` when building with a JDK newer than JDK 8, as the docs claim that the classes from the `tools.jar` are now automatically available via the `ApplicationClassloader` but MPS completely fails when running on JDK 9+. It can't even build stubs for the JDK in these cases then. 

I think we should add similar code blocks to the other MPS based build scripts as well [(IETS3](https://github.com/IETS3/iets3.opensource), [MPS extensions](https://github.com/JetBrains/MPS-extensions), etc)

**Pull request merged**
