### PR TITLE
add MPS versions back to file names

### PR DESCRIPTION
**Pull request by coolya**
As @eugenschindler reported in #1722 due to our build infrastructure changes, the build number was no longer part of the file name that was uploaded to github. 

The feature has been added again. You can have a look on a release here:

https://github.com/mbeddr/mbeddr.core/releases/tag/nightly-557

### CODE REVIEW

**Comment by eugenschindler** [comment]
Looks perfect! Thanks :)
Just a small question before merging: do you think it's a good idea to call it platform-distribution-MPS2017.3.2.zip instead of platform-distribution-2017.3.2.zip? This would make it more explicit that it's based on the MPS version. Or is there a good reason not to do that?

**Comment by coolya** [comment]
Ho about including both, the MPS version and the mbeddr build number in the file name like `platform-distribution-1.0.19813.671048f-MPS-2017.3.2.zip`? That build number is also a valid version number to resolve mbeddr from our nexus.

**Comment by eugenschindler** [comment]
If that is not too much work, that would definitely be the most ideal solution!

**Comment by eugenschindler** [comment]
Super! Thanks a lot!!

**Comment by eugenschindler** [comment]
Hi Kolja,
Unfortunately, we lost the MPS version again in the build. I see again that the allInOne zips don't have an MPS version. Would it be possible to bring it back? I have no idea right now which version of MPS to use with, for example, nighly 571 (currently the newest).

**Pull request merged**
