### PR TITLE
doc.spreadsheet: remove core.base dependency

### PR DESCRIPTION
**Pull request by coolya**

### CODE REVIEW

**Comment by stephaneberle9** [comment]
Using INamedConcept instead of IIdentifierNamedConcept to get rid of the com.mbeddr.core.base dependency is perfectly fine with me.

**Comment by arimer** [comment]
What about the addition constraints, which were inherited from the IIdentifierNamedConcept? Style and Workbook do not need them any longer?

**Comment by coolya** [comment]
@arimer please check in the upstream RCP if this dependency change would fix the issues we had. Since I don't have the RCP here it's hard for me to verify.

**Comment by arimer** [comment]
Hey, the problem is still there because there is a  dependency to `mbeddr.core.modules`
image

**Comment by coolya** [comment]
There is also a dependency on the modules gen generator which can't get resolved. I will try to find a workaround for that as well.

**Comment by stephaneberle9** [comment]
@arimer I don't think that the quite C-specific property contraint from IIdentifierNamedConcept is meaningful to workbook and style names in spreadsheets. Most probably, the IIdentifierNamedConcept has only been used out of habit when the workbook and stype concepts have been created but not because there is any real need for that.

**Comment by coolya** [comment]
@arimer @joao-silveira can one of you please verify that these changes fix the problem in the upstream projects that only depend on the platform? 

If so please add a positive review and we can merge it.

**Comment by arimer** [comment]
Picked the latest plugins from team city and tried it out. Error in the modules pool is gone for me.
See: 
image

**Pull request merged**
