### PR TITLE
[breaking] Remove spawner and debugger

### PR DESCRIPTION
**Pull request by sergej-koscejev**
This was previously submitted as #2272 and now I'm submitting it again, rebased on top of 2022.2.

To reiterate, here are the reasons for removing the debugger and spawner from https://github.com/mbeddr/mbeddr.core/pull/2272#issuecomment-1889958600.

1. Spawner and debugger are somehow special and make it impossible to simply open the entire mbeddr project (using tools/BigProject) and build it in MPS. Language com.mbeddr.core.debug cannot be loaded if spawner is not installed as a plugin.

2. Spawner contains some native libraries under tools/mbeddr.spawner/lib/spawner but it's not clear where they come from, there's no library for AArch64 Mac, and macosx..x86_64 folder is likely misspelled (extra period), making me wonder how this thing could ever have worked on any Mac.

## Checklist for creating a good PR (can be deleted)

- [x] I've described my change in the CHANGELOG.md if it is visible to users of the platform (**mandatory**).
- [x] I've selected the correct [base branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request).
- [ ] I have checked my code (edge cases, no errors) and corrected any misspellings.
- [ ] I have added comments to my code in areas where the code is hard to understand.
- [ ] I've created a new language/solution.
    - [ ] I've added the language/solution to the build script ([tutorial in readme](https://github.com/mbeddr/mbeddr.core#contributing-to-the-mbeddrplatform))
    - [ ] I've added a sandbox that showcases the language.
    - [ ] There is some kind of documentation available in the repository or somewhere else [e.g. [MPS Platform Docs](http://mbeddr.com/mps-platform-docs/platform_essentials/com_mbeddr_mpsutil/)].
- [x] I've introduced a breaking change.
     - [x] I've made it clear that a change is breaking e.g. [breaking] prefix in the title
     - [ ] I have written new tests/changed old tests.
     - [ ] I have created migrations when necessary (e.g., deprecation of concepts, properties, enumeration values).
     - [ ] I haven't removed concepts, properties, references, or children without deprecating them first.
     - [ ] I have moved nodes or models by using the refactoring move action.

### CODE REVIEW

**Review by alexanderpann — CHANGES_REQUESTED** [review]
Thanks for the big PR! A few things:
- Can you please remove the entries from the .gitignore as well?
- The old documentation about the debugger can also be removed: http://127.0.0.1:63320/node?ref=r%3A5ff4e1a0-ec5b-4e83-a849-9e8c2c4adf79%28com.mbeddr.tutorial.documentation.ug.ctooling%29%2F620304030110802052 as well as documentation/userguide/020-core/030-debugging.ltx and its usage
- BigProjectGenerator still references Eclipse.Debugger
- I still see 496 references to the language com.mbeddr.core.debug in the XML files.

**Comment by sergej-koscejev** [comment]
@alexanderpann I fixed all points except the last one. I can't seem to get rid of com.mbeddr.core.debug neither by running Force Save All from MPS, nor by attempting a migration. And I don't want to edit the XMLs by hand out of principle.

**Comment by sergej-koscejev** [comment]
Forgot to fix the documentation.

Also, I decided to fix the module descriptors by hand after all. I think getting rid of the debugger is worth disobeying the principles for once :)

**Comment by sergej-koscejev** [comment]
@alexanderpann your comments should be addressed now, please take another look.

**Review by alexanderpann — CHANGES_REQUESTED** [review]
I still see a few imports:

Screenshot 2024-09-15 at 19 44 07

- Can you check if the folder code/languages/com.mbeddr.core/solutions/com.mbeddr.core.debugger.default is removed for you?

**Comment by sergej-koscejev** [comment]
> I still see a few imports:

Should be gone now.
 
> * Can you check if the folder code/languages/com.mbeddr.core/solutions/com.mbeddr.core.debugger.default is removed for you?

Yes, it's removed.

**Review by alexanderpann — APPROVED** [review]

**Review by alexanderpann — APPROVED** [review]

**Pull request merged**
