### PR TITLE
Feature/accent 2428

### PR DESCRIPTION
**Pull request by DineshLMS**
Hi,

Diagram palatte is not listing any entries of blocks. Suspecting this could be the same problem as #1624 .
The detailed explanation of the defect is present in accent-2428 YT issue.

Please review and merge.

Regards,
Dinesh

### CODE REVIEW

**Comment by slisson** [comment]
I fixed it in c65db7d09ee98dcab95355e676f62b0cca3a5576 as suggested but also removed some duplicate code.

**Comment by DineshLMS** [comment]
okay. Could you please cherry pick the same to milestone/v16-1 ? (if it is not already done)

**Comment by slisson** [comment]
It's already done.

**Comment by DineshLMS** [comment]
Thank you very much @slisson

**Pull request closed without merging**
